spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.99.100/sell?characterEncoding=utf-8&useSSl=false
  jpa:
    show-sql: true
  redis:
    host: 192.168.99.100
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8086
env:
  dev
